name: Deploy Website to HostGator

on:
  push:
    branches:
      - main
    paths:
      - 'Arkhe_Aula_Web/**'

jobs:
  FTP-Deploy-Action:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 69.6.201.149
        username: Arkhe_Soft@arkhegroup.com
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./Arkhe_Aula_Web/
        server-dir: public_html/arkhe-aula/
